var other_matters = "Other Matters\nI. Reiteration of the Department's House Rules\n\tII. Revisit 5s\n\tIII.\n\tIV.\n\tIV\n\nThere having no other matters to be dicussed the meeting is adjourned.";

var pdrm_discussion = "Personnel Development and Records Management (PDRM) Targets<br>I.&nbsp;&nbsp;&nbsp; Hiring and Recruitment<br>II.&nbsp;&nbsp;&nbsp; Performance and behavioral monitoring of employees (targets and measures, established office policies)<br>a. Behavioral Monitoring Report Generation (Absences, Tardiness, Under time and Half day)<br>b. Generation and validation of Draft DTR from Attendance Management System<br>c. Generation of Monthly Behavioral Monitoring Report<br>d. Generation of Spot-Checking Report<br>e. E-logbook Monitoring<br>III.&nbsp;&nbsp;&nbsp; Effectively implemented personnel development activities/trainings/coaching and mentoring<br>a.&nbsp;&nbsp;&nbsp; Training Preparation (Formulation of Personnel Development Plan and Training Manual)<br>b.&nbsp;&nbsp;&nbsp; Training Implementation<br>c.&nbsp;&nbsp;&nbsp; Conduct of planned trainings<br>d.&nbsp;&nbsp;&nbsp; Tabulation and Analysis of Evaluation form<br>IV.&nbsp;&nbsp;&nbsp; Enhanced CHUDDIA by initiating the records management system both physical and data base<br>a.&nbsp;&nbsp;&nbsp; Records Room Management (Transfer of records and facilitate request forms)<br>b.&nbsp;&nbsp;&nbsp; Inbound/Outbound Document Management<br>c.&nbsp;&nbsp;&nbsp; Records Management Filing (Both Physical and data base) (Public Server, soft copies, 201 filing and correspondence)<br>d.&nbsp;&nbsp;&nbsp; <br>V.&nbsp;&nbsp;&nbsp; Others<br><br>"

var fsm_discussion = "Finance and Supply Management (F&amp;SM) Targets<br>I.&nbsp;&nbsp;&nbsp; Regularly Implemented Documented/liquidated the Department Finances with prompt budget preparations and requests<br>a.&nbsp;&nbsp;&nbsp; PPMP 2021 Preparation (draft)<br>II.&nbsp;&nbsp;&nbsp; Reported Department�s Quarterly Financial Status and Inventory of Supplies<br>a.&nbsp;&nbsp;&nbsp; Preparation of Casual/Regular Payroll/RATA<br>b.&nbsp;&nbsp;&nbsp; Preparation of Job Order Payroll<br>c.&nbsp;&nbsp;&nbsp; Preparation of Vouchers, Financial Docs, Reimbursement, Cash Advance<br>d.&nbsp;&nbsp;&nbsp; Budget Monitoring / Cash Flow/Financial Status<br><br>III.&nbsp;&nbsp;&nbsp; Effectively prepared and submitted its AIP and Budget Proposal for 2021 and within scheduled time<br>a.&nbsp;&nbsp;&nbsp; Supplies Monitoring (requisition facilitation, audit, inventory, monitoring report)<br>b.&nbsp;&nbsp;&nbsp; Equipment Usage &amp; Semestral Inventory (Facilitation, Monitoring)<br>c.&nbsp;&nbsp;&nbsp; FRIMP-CDOR payment preparation &amp; processing<br>IV.&nbsp;&nbsp;&nbsp; Others<br><br><br>"

var omss_discussion = "Office Maintenance &amp; Support Services (OMSS) Targets<br>I.&nbsp;&nbsp;&nbsp; Regularly provided the logistical support in the program implementation with no adverse feedback within scheduled time<br>a.&nbsp;&nbsp;&nbsp; Daily Office Cleaning<br>b.&nbsp;&nbsp;&nbsp; Office Safety &amp; Security<br>c.&nbsp;&nbsp;&nbsp; Monthly General Cleaning<br>II.&nbsp;&nbsp;&nbsp; Efficiently managed and maintained its equipment, utilities and facilities as manifested in the outstanding Implementation of Department�s Programs<br>a.&nbsp;&nbsp;&nbsp; Weekly Equipment Inspection<br>b.&nbsp;&nbsp;&nbsp; Equipment Maintenance<br>III.&nbsp;&nbsp;&nbsp; Documented and Reported its utilization and inventory in the Department�s Quarterly meeting<br>a.&nbsp;&nbsp;&nbsp; Transportation Services<br>b.&nbsp;&nbsp;&nbsp; Daily Vehicle Inspection<br>c.&nbsp;&nbsp;&nbsp; Gasoline Inspection &amp; Facilitation<br>d.&nbsp;&nbsp;&nbsp; Transportation Maintenance<br>IV.&nbsp;&nbsp;&nbsp; Others<br><br><br>"

var assd_agenda = "Update on PDRM's Targets\nUpdate on F&SM's Targets\nUpdate on OMSS' Targets";
var assd_discussion = pdrm_discussion + "<br>" + fsm_discussion + "<br>" + omss_discussion + other_matters;

//hcd
var hrod_discussion = "Human Resource and Organizational Development (HROD) Targets<br>I.&nbsp;&nbsp; &nbsp;Trained and Developed Community Leaders and Strengthen their Organizations &nbsp;<br>a.&nbsp;&nbsp; &nbsp;Organizational Development - Session 1<br>b.&nbsp;&nbsp; &nbsp;Documentation, Periodic Evaluation and Reporting of the Training (including the SEP and CSEM Training)<br>c.&nbsp;&nbsp; &nbsp;Assistance and Monitoring of UCHG participation of HOA beneficiaries, Communal Gardens and CDC and Market Days (X)<br>d.&nbsp;&nbsp; &nbsp;HOA Solid Waste Management Monitoring and participation of HOA beneficiaries in the Barangay and City-wide Campaign<br>e.&nbsp;&nbsp; &nbsp;Engagement of Youth in the Relocation and Barangay<br>f.&nbsp;&nbsp; &nbsp;Updating of HLURB/DSHUD Required Activities and Reports of 20 HOAs and Assistance of HLURB/DSHUD Applications and Reports Submission<br>g.&nbsp;&nbsp; &nbsp;Attending HOA Concerns and Attendance in their Monthly Federation Meetings (X) with Prepared Reports of CHUDD's Activities<br>II.&nbsp;&nbsp; &nbsp;Assisted in the CHUDDIS-generated inventory of the household members and completion of their required documents especially for titling<br>a.&nbsp;&nbsp; &nbsp;House to House Updating of HOA beneficiary family status - priority HOAs for titling, Assistance of Lacking Requirements especially their TIN, and others<br>b.&nbsp;&nbsp; &nbsp;Encoding in CHUDDIS, Recording and Consolidation of 'A' files of beneficiary Beneficiaries/HOAs for titling<br>III.&nbsp;&nbsp; &nbsp;Others<br><br>"

var sep_discussion = "Social Entrepreneurship Program (SEP) Targets<br>I.&nbsp;&nbsp;&nbsp; Sustained the 8/11 SEPs (1st Batch), with at least 1 to 2 champion projects (silk worm, clustered rice selling projects and CHB productions)<br>a.&nbsp;&nbsp;&nbsp; Livelihood Fund Bank Withdrawal<br>b.&nbsp;&nbsp;&nbsp; Product and Marketing Improvement<br>c.&nbsp;&nbsp;&nbsp; Financial &amp; Management Monthly Reports<br>d.&nbsp;&nbsp;&nbsp; Submits audited Financial Reports<br>e.&nbsp;&nbsp;&nbsp; Conduct consultation/feedback meetings and/or mentoring with Livelihood Management about audited and assessed/evaluated FRs and Management Reports<br>II.&nbsp;&nbsp;&nbsp; Capacitate and Engaged their 20 Core leaders in the SE Projects of their HOA Members<br>a.&nbsp;&nbsp;&nbsp; HCD Integrated Program Implementation<br>b.&nbsp;&nbsp;&nbsp; Coordinate with HROD and CSEM for the implementation of the HCD Integrated Program<br>III.&nbsp;&nbsp;&nbsp; Initiated SEP for the other identified potential HOAs<br>a.&nbsp;&nbsp;&nbsp; Assist business proposal making of 7/20 HOAs under HCD integrated Program<br>b.&nbsp;&nbsp;&nbsp; Market Days<br>c.&nbsp;&nbsp;&nbsp; Coordinates with CDO Technical Vocation Institute, CDRRMD and CID<br>d.&nbsp;&nbsp;&nbsp; Other Special Projects<br>IV.&nbsp;&nbsp;&nbsp; Others<br><br><br>"

var csem_discussion = "Community Services and Estate Management Section (CSEM) Targets<br>I.&nbsp;&nbsp;&nbsp; Capacitate and engaged their 20 Core Leaders in the HOA and subdivision Management<br>a.&nbsp;&nbsp;&nbsp; Conduct Module 1 HOA training<br>b.&nbsp;&nbsp;&nbsp; Documentation, Weekly Evaluation/Clinquing, and Joint Evaluation (inter section X) and Reporting<br>II.&nbsp;&nbsp;&nbsp; Provided and Maintained Substantial Basic Services of the Relocation Areas:&nbsp;&nbsp; <br>a.&nbsp;&nbsp;&nbsp; Facilitate the release of CAF<br>b.&nbsp;&nbsp;&nbsp; Demolition of illegal Structure in Indahag phase 1, Habitat Phase 3, Old Filchi, LGU 19 and Mahogany<br>c.&nbsp;&nbsp;&nbsp; Conduct Housing Unit Inventory CDORSHIP Phase 3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Habitat for Humanity, P3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>d.&nbsp;&nbsp;&nbsp; Attend referrals on community concerns and disputes with HOA grievance committee and inspection of business permit application inside the relocation&nbsp;&nbsp; <br>III.&nbsp;&nbsp;&nbsp; 60% Updated Master List per HOA and attended delinquent beneficiaries/occupants in coordination with the trained HOAs Grievance Committee<br>IV.&nbsp;&nbsp;&nbsp; Attend 100% referrals on IDPS Affected by Natural Desaster, Demolition, fire and other related concerns<br>a.&nbsp;&nbsp;&nbsp; Attend committee meeting on IDPs affected by demolition, fire and other related disaster<br>b.&nbsp;&nbsp;&nbsp; Assist and Facilitate the transfer of IDPs to their permanent relocation or temporary shelter<br>V.&nbsp;&nbsp;&nbsp; Others<br><br><br>"

var hcd_agenda = "Update on HROD's Targets\nUpdate on SEP's Targets\nUpdate on CSEM' Targets";
var hcd_discussion = hrod_discussion + "<br>" + sep_discussion + "<br>"+csem_discussion
//lhe
var labs_discussion = "Land Acquisition and Banking Section (LABS) Targets<br>I.&nbsp;&nbsp; &nbsp;40has acquired land with 60% buildability<br>a.&nbsp;&nbsp; &nbsp;Endorsement to City Legal for review and computation of expenses for CAF<br>II.&nbsp;&nbsp; &nbsp;Finalized all transfer of Titles of the acquired properties from previous years (2017-2019)<br>a.&nbsp;&nbsp; &nbsp;Release of E-CAR at BIR (P. Rico, Jaraula, Pung, Natividad &amp; Ladaran)<br>b.&nbsp;&nbsp; &nbsp;Release of transferred Title at ROD (Larede, O. Rico &amp; L. Sambaan)<br>III.&nbsp;&nbsp; &nbsp;Identified new properties and initiated negotiations with land owners for 2021 Land Acquisition and Banking<br>a.&nbsp;&nbsp; &nbsp;Pro-action/ Identification of prospective land suitable for Socialized Housing Project<br>IV.&nbsp;&nbsp; &nbsp;Documented and recorded all acquired lands of the City for Socialized Housing and all existing relocation sites of the City<br>a.&nbsp;&nbsp; &nbsp;Updating of record<br>V.&nbsp;&nbsp; &nbsp;Others <br><br>"
var hds_discussion = "Housing Development Section (HDS) Targets<br>I.&nbsp;&nbsp;&nbsp; At least 500 Housing units available of ready for occupancy and developed new housing/subdivision plans<br>a.&nbsp;&nbsp;&nbsp; Field Reporting and Reporting of Well Development at Pahiron, Lumbia (with Temporary Pump single phase)<br>b.&nbsp;&nbsp;&nbsp; Field Monitoring and Reporting of Construction of 66 units Transitory Shelter Facilities<br>c.&nbsp;&nbsp;&nbsp; Field Monitoring and Reporting of Bayanihan Vill. P1A, Water Pipe Laying (Level 3)<br>d.&nbsp;&nbsp;&nbsp; Field Monitoring and Reporting of Balubal Relocation Projects P2 (Land Development)<br>II.&nbsp;&nbsp;&nbsp; Land Development and Initial Housing Construction of Existing Project with at least and average of 20% land development<br>a.&nbsp;&nbsp;&nbsp; Field Monitoring and Reporting of GK-SMC Balubal Road Concreting<br>b.&nbsp;&nbsp;&nbsp; Field Monitoring and Reporting of Pagatpat Resettlement Project phase 2 (Land Development - macadam only)<br>c.&nbsp;&nbsp;&nbsp; Field Monitoring and Reporting of Pagatpat Valley Residences (Land Development)<br>III.&nbsp;&nbsp;&nbsp; Implemented 1 New Ground Breaking<br>a.&nbsp;&nbsp;&nbsp; Redevelopment Plans of Existing Relocation Areas<br>b.&nbsp;&nbsp;&nbsp; New Housing development plan of the acquired Lot and Ground Breaking<br>IV.&nbsp;&nbsp;&nbsp; Others<br><br><br>"
var es_discussion = "Emancipation Section (ES) Targets<br>I.&nbsp;&nbsp;&nbsp; Distributed titles in GK-SMC for at least 325 Good Standing Beneficiaries<br>a.&nbsp;&nbsp;&nbsp; Facilitated completion of Tax Declaration for lot and building<br>b.&nbsp;&nbsp;&nbsp; Facilitated verification of A-files for TIN Application and examined documents for application of ECAR<br>c.&nbsp;&nbsp;&nbsp; Approval of Beneficiaries for Notary Acknowledgment and BIR ECAR Application<br>d.&nbsp;&nbsp;&nbsp; Facilitated Application of ECAR at BIR including payment of taxes to Accredited Bank/s, and processing of ROD registration fees payments<br>e.&nbsp;&nbsp;&nbsp; Verified TINs and or processed 80-100% TIN Applications of the Beneficiaries / Awardees<br>f.&nbsp;&nbsp;&nbsp; Processed assessment, routing of deeds, online application of Donor's tax and release of 80-100% ECARs / ONETT<br>g.&nbsp;&nbsp;&nbsp; Facilitated/Examined documents application for issuance of individual titles as compliant to Registration Act 496 in the name of Beneficiary<br>h.&nbsp;&nbsp;&nbsp; Processed entry, encoding and releasing of 80-100% Titling of GK SMC Balubal Deeds of Donation<br>II.&nbsp;&nbsp;&nbsp; Signing of Deed of Sale in CDORSHP Phase 3 for the Good Standing Beneficiaries<br>a.&nbsp;&nbsp;&nbsp; Facilitated the process including request of payment for individual baby titles of CDORSHP-I Phase 3 @ ROD<br>b.&nbsp;&nbsp;&nbsp; Facilitate entry, encoding and checking of CDORSHP-I Phase 3 at ROD<br>c.&nbsp;&nbsp;&nbsp; Identified/verified documents and A-files, and TIN verification of the beneficiaries of CDORSHP-I Phase 3 (Habitat for Humanity)<br>d.&nbsp;&nbsp;&nbsp; Facilitated passage of HLURB License to Sell of CDORSHP-I Phase 3<br>III.&nbsp;&nbsp;&nbsp; Initiated the documentation of the Beneficiaries in Indahag Phase 2<br>a.&nbsp;&nbsp;&nbsp; Processed and facilitated submission of Approved DENR Subdivision Application based on Alteration of Plan<br>IV.&nbsp;&nbsp;&nbsp; Others<br><br><br>"
var lhe_agenda = "Update on LABS' Targets\nUpdate on HDS' Targets\nUpdate on ES' Targets";
var lhe_discussion = labs_discussion + "<br>" + hds_discussion + "<br>" + es_discussion
//lhe
//udp

var ups_discussion = " Urban Planning Section (UPS) Targets I. Conduct of the Urban Forum 2020 A. Sectoral Discussion #1 for the City Department heads B. Sectoral Discussion #2 for the Urban Poor and Barangay Officials II. Policy Advocacy and Development thru LHIAC and LHB A. Preparation for Policy Paper/Proposal (coordination meetings and drafting) B. Submission of proposal to LHIAC/LHB, City Legal and OSM for endorsement to City Council C. Lobby Councilors for passage of policy / Secure Ordinance D. Facilitate conduct of regular LHIAC meetings E. Facilitate conduct of regular LHB meetings III. Assistance to Barangays for their BSP to come up with SHP A. Facilitate the application of Macasandig HOA for their application for CMP B. Facilitate the organization of barangay 24 for their possible BSP IV. Development of Housing Project through BALAI, CMP and/or forms of partnerships A. MOA/Proposal Preparation and Submission to all parties for initial review and approval (DHSUD, SMDC, City Mayor); coordinate with LHE for inputs and attachments "
var aps_discussion = "Application and Profiling Section (APS) Targets<br>I.&nbsp;&nbsp;&nbsp; Produce a City-wide Listing f ISF <br>A.&nbsp;&nbsp;&nbsp; Planning, Consultations with ABC, and other agencies<br>B.&nbsp;&nbsp;&nbsp; Mobilizations, preparations of Survey Tools, Training of Brgy. Point Persons<br>C.&nbsp;&nbsp;&nbsp; Conduct of ISF Listing in the 8 Pilot Brgys of BSP, and within numbered brgys<br>II.&nbsp;&nbsp;&nbsp; CHUDDIS-generated 1500 qualified ISF Applicants<br>A.&nbsp;&nbsp;&nbsp; Selection Committee Meeting<br>B.&nbsp;&nbsp;&nbsp; Raffling<br>C.&nbsp;&nbsp;&nbsp; Issuance of Entry Pass<br>D.&nbsp;&nbsp;&nbsp; Engagements and Meetings with NHA, SHFC, CSWD, DSWD and Barangay<br>E.&nbsp;&nbsp;&nbsp; Monthly General Assemblies or Meeting with Officers and Board Members for Balubal Heights HOA<br>III.&nbsp;&nbsp;&nbsp; Others <br><br>"
var ict_discussion = "Information &amp; Communication Technology Section (ICT) Targets<br>I.&nbsp;&nbsp;&nbsp; Full Implementation of CHUDDIS and CHUDDIA, Website, and Generated Monthly Reports<br>A.&nbsp;&nbsp;&nbsp; Generation of CHUDDIS Monthly Reports (ISFs, Beneficiaries, Applicants)<br>B.&nbsp;&nbsp;&nbsp; Generation of CHUDDIA Monthly Reports (logbook, PAR, MOM, Comms.)<br>C.&nbsp;&nbsp;&nbsp; Implementation of Text Blast&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>D.&nbsp;&nbsp;&nbsp; Feedback enhancement for existing system<br>E.&nbsp;&nbsp;&nbsp; Implementation of OPCR and integration to logbook&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>F.&nbsp;&nbsp;&nbsp; Website Enhancement&nbsp; <br>II.&nbsp;&nbsp;&nbsp; Initiated IT-based System (From ISF to Family Beneficiary)<br><br>"
var udp_agenda = "Update on UPS' Targets\nUpdate on APS' Targets\nUpdate on ICT's Targets";
var udp_discussion = ups_discussion + "<br>" + aps_discussion + "<br>" + ict_discussion